name: Test deployment

on:
  workflow_dispatch: # Makes workflow manually runnable
    branches:
      - main
  pull_request:
    paths:
      - docs/**
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs/website
    steps:
      - uses: actions/checkout@v3
        working-directory: ${{env.working-directory}}
      - uses: actions/setup-node@v3
        working-directory: ${{env.working-directory}}
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Test build website
        run: npm run build
        working-directory: ${{env.working-directory}}
